### ISSUE TITLE
Printing fw_req returns error

### ISSUE THREAD

**Issue by harshitgarg22** [ease-lab/vSwarm-proto#2]
In clients like hipstershop and hotel service, printing `fw_req` to get information about the message request leads to an error.
```bash
grpcclient/hipstershop_clients.go:132:43: copylocks: call of fmt.Sprintf copies lock value: github.com/ease-lab/vSwarm-proto/proto/hipstershop.AddItemRequest contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
                msg = fmt.Sprintf("req: %+v resp: %+v", fw_req, fw_res)
```

This happens because the Request struct contains MessageState, which has a mutex lock to prevent copying ([see stackoverflow for reference](https://stackoverflow.com/a/64183968)).
And I think while copying printf creates a shallow copy of the variable.

I see two possible approaches,
1. Remove the printf statements entirely
2. Refactor them as debug logging, create a deep copy of the variable (if possible), and then log it. This would also prevent benchmark spending time on something not related to actual processing of the function.

**Comment by harshitgarg22** [comment]
I have tried to manually add fields in #5.

**Comment by dhschall** [comment]
Thanks for reporting this bug!!
So most important thing is that its fast.
However, I think it is also important that we know when something fails.
What do you think is the best?

**Comment by dhschall** [comment]
Manually adding the field is ok but I think its effort.
Whould it be possible and faster to log the request before sending and the reponse afterwards??
Something like this:
```
	case "GetProduct", "1": // Method 2: GetProduct
		fw_req := pb.GetProductRequest{
			Id: payload,
		}
                dbg.Printf("Call:  GetProduct(%+v)" ,fw_req)
		var fw_res *pb.Product
		fw_res, err = c.client.GetProduct(c.ctx, &fw_req)
                dbg.Printf("resp: %+v" ,fw_res)
		msg = fmt.Sprintf("resp: %+v", payload, fw_res)
```
