### ISSUE TITLE
Please apply this linkchecker workaround for the links to GitHub docs

### ISSUE THREAD

**Issue by ustiugov** [ease-lab/vSwarm-proto#8]
More details provided by this GitHub action's maintainer [here](https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/136#issuecomment-1117148640).

**Comment by harshitgarg22** [comment]
Fixed in https://github.com/ease-lab/vSwarm-proto/commit/34e74c9cb2c4e45a354275a52fa702f9ffad3514
Pushed to main directly, will remember to make a PR from next time.
